/*
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

public class Another {
  public Another() {
    System.out.println("Another Instance");
  }
  public static void m0() {}
  public static void m1() {}
  public static void m2() {}
  public static void m3() {}
  public static void m4() {}
  public static void m5() {}
  public static void m6() {}
  public static void m7() {}
  public static void m8() {}
  public static void m9() {}
  public static void m10() {}
  public static void m11() {}
  public static void m12() {}
  public static void m13() {}
  public static void m14() {}
  public static void m15() {}
  public static void m16() {}
  public static void m17() {}
  public static void m18() {}
  public static void m19() {}
  public static void m20() {}
  public static void m21() {}
  public static void m22() {}
  public static void m23() {}
  public static void m24() {}
  public static void m25() {}
  public static void m26() {}
  public static void m27() {}
  public static void m28() {}
  public static void m29() {}
  public static void m30() {}
  public static void m31() {}
  public static void m32() {}
  public static void m33() {}
  public static void m34() {}
  public static void m35() {}
  public static void m36() {}
  public static void m37() {}
  public static void m38() {}
  public static void m39() {}
  public static void m40() {}
  public static void m41() {}
  public static void m42() {}
  public static void m43() {}
  public static void m44() {}
  public static void m45() {}
  public static void m46() {}
  public static void m47() {}
  public static void m48() {}
  public static void m49() {}
  public static void m50() {}
  public static void m51() {}
  public static void m52() {}
  public static void m53() {}
  public static void m54() {}
  public static void m55() {}
  public static void m56() {}
  public static void m57() {}
  public static void m58() {}
  public static void m59() {}
  public static void m60() {}
  public static void m61() {}
  public static void m62() {}
  public static void m63() {}
  public static void m64() {}
  public static void m65() {}
  public static void m66() {}
  public static void m67() {}
  public static void m68() {}
  public static void m69() {}
  public static void m70() {}
  public static void m71() {}
  public static void m72() {}
  public static void m73() {}
  public static void m74() {}
  public static void m75() {}
  public static void m76() {}
  public static void m77() {}
  public static void m78() {}
  public static void m79() {}
  public static void m80() {}
  public static void m81() {}
  public static void m82() {}
  public static void m83() {}
  public static void m84() {}
  public static void m85() {}
  public static void m86() {}
  public static void m87() {}
  public static void m88() {}
  public static void m89() {}
  public static void m90() {}
  public static void m91() {}
  public static void m92() {}
  public static void m93() {}
  public static void m94() {}
  public static void m95() {}
  public static void m96() {}
  public static void m97() {}
  public static void m98() {}
  public static void m99() {}
  public static void m100() {}
  public static void m101() {}
  public static void m102() {}
  public static void m103() {}
  public static void m104() {}
  public static void m105() {}
  public static void m106() {}
  public static void m107() {}
  public static void m108() {}
  public static void m109() {}
  public static void m110() {}
  public static void m111() {}
  public static void m112() {}
  public static void m113() {}
  public static void m114() {}
  public static void m115() {}
  public static void m116() {}
  public static void m117() {}
  public static void m118() {}
  public static void m119() {}
  public static void m120() {}
  public static void m121() {}
  public static void m122() {}
  public static void m123() {}
  public static void m124() {}
  public static void m125() {}
  public static void m126() {}
  public static void m127() {}
  public static void m128() {}
  public static void m129() {}
  public static void m130() {}
  public static void m131() {}
  public static void m132() {}
  public static void m133() {}
  public static void m134() {}
  public static void m135() {}
  public static void m136() {}
  public static void m137() {}
  public static void m138() {}
  public static void m139() {}
  public static void m140() {}
  public static void m141() {}
  public static void m142() {}
  public static void m143() {}
  public static void m144() {}
  public static void m145() {}
  public static void m146() {}
  public static void m147() {}
  public static void m148() {}
  public static void m149() {}
  public static void m150() {}
  public static void m151() {}
  public static void m152() {}
  public static void m153() {}
  public static void m154() {}
  public static void m155() {}
  public static void m156() {}
  public static void m157() {}
  public static void m158() {}
  public static void m159() {}
  public static void m160() {}
  public static void m161() {}
  public static void m162() {}
  public static void m163() {}
  public static void m164() {}
  public static void m165() {}
  public static void m166() {}
  public static void m167() {}
  public static void m168() {}
  public static void m169() {}
  public static void m170() {}
  public static void m171() {}
  public static void m172() {}
  public static void m173() {}
  public static void m174() {}
  public static void m175() {}
  public static void m176() {}
  public static void m177() {}
  public static void m178() {}
  public static void m179() {}
  public static void m180() {}
  public static void m181() {}
  public static void m182() {}
  public static void m183() {}
  public static void m184() {}
  public static void m185() {}
  public static void m186() {}
  public static void m187() {}
  public static void m188() {}
  public static void m189() {}
  public static void m190() {}
  public static void m191() {}
  public static void m192() {}
  public static void m193() {}
  public static void m194() {}
  public static void m195() {}
  public static void m196() {}
  public static void m197() {}
  public static void m198() {}
  public static void m199() {}
  public static void m200() {}
  public static void m201() {}
  public static void m202() {}
  public static void m203() {}
  public static void m204() {}
  public static void m205() {}
  public static void m206() {}
  public static void m207() {}
  public static void m208() {}
  public static void m209() {}
  public static void m210() {}
  public static void m211() {}
  public static void m212() {}
  public static void m213() {}
  public static void m214() {}
  public static void m215() {}
  public static void m216() {}
  public static void m217() {}
  public static void m218() {}
  public static void m219() {}
  public static void m220() {}
  public static void m221() {}
  public static void m222() {}
  public static void m223() {}
  public static void m224() {}
  public static void m225() {}
  public static void m226() {}
  public static void m227() {}
  public static void m228() {}
  public static void m229() {}
  public static void m230() {}
  public static void m231() {}
  public static void m232() {}
  public static void m233() {}
  public static void m234() {}
  public static void m235() {}
  public static void m236() {}
  public static void m237() {}
  public static void m238() {}
  public static void m239() {}
  public static void m240() {}
  public static void m241() {}
  public static void m242() {}
  public static void m243() {}
  public static void m244() {}
  public static void m245() {}
  public static void m246() {}
  public static void m247() {}
  public static void m248() {}
  public static void m249() {}
  public static void m250() {}
  public static void m251() {}
  public static void m252() {}
  public static void m253() {}
  public static void m254() {}
  public static void m255() {}
  public static void m256() {}
  public static void m257() {}
  public static void m258() {}
  public static void m259() {}
  public static void m260() {}
  public static void m261() {}
  public static void m262() {}
  public static void m263() {}
  public static void m264() {}
  public static void m265() {}
  public static void m266() {}
  public static void m267() {}
  public static void m268() {}
  public static void m269() {}
  public static void m270() {}
  public static void m271() {}
  public static void m272() {}
  public static void m273() {}
  public static void m274() {}
  public static void m275() {}
  public static void m276() {}
  public static void m277() {}
  public static void m278() {}
  public static void m279() {}
  public static void m280() {}
  public static void m281() {}
  public static void m282() {}
  public static void m283() {}
  public static void m284() {}
  public static void m285() {}
  public static void m286() {}
  public static void m287() {}
  public static void m288() {}
  public static void m289() {}
  public static void m290() {}
  public static void m291() {}
  public static void m292() {}
  public static void m293() {}
  public static void m294() {}
  public static void m295() {}
  public static void m296() {}
  public static void m297() {}
  public static void m298() {}
  public static void m299() {}
  public static void m300() {}
  public static void m301() {}
  public static void m302() {}
  public static void m303() {}
  public static void m304() {}
  public static void m305() {}
  public static void m306() {}
  public static void m307() {}
  public static void m308() {}
  public static void m309() {}
  public static void m310() {}
  public static void m311() {}
  public static void m312() {}
  public static void m313() {}
  public static void m314() {}
  public static void m315() {}
  public static void m316() {}
  public static void m317() {}
  public static void m318() {}
  public static void m319() {}
  public static void m320() {}
  public static void m321() {}
  public static void m322() {}
  public static void m323() {}
  public static void m324() {}
  public static void m325() {}
  public static void m326() {}
  public static void m327() {}
  public static void m328() {}
  public static void m329() {}
  public static void m330() {}
  public static void m331() {}
  public static void m332() {}
  public static void m333() {}
  public static void m334() {}
  public static void m335() {}
  public static void m336() {}
  public static void m337() {}
  public static void m338() {}
  public static void m339() {}
  public static void m340() {}
  public static void m341() {}
  public static void m342() {}
  public static void m343() {}
  public static void m344() {}
  public static void m345() {}
  public static void m346() {}
  public static void m347() {}
  public static void m348() {}
  public static void m349() {}
  public static void m350() {}
  public static void m351() {}
  public static void m352() {}
  public static void m353() {}
  public static void m354() {}
  public static void m355() {}
  public static void m356() {}
  public static void m357() {}
  public static void m358() {}
  public static void m359() {}
  public static void m360() {}
  public static void m361() {}
  public static void m362() {}
  public static void m363() {}
  public static void m364() {}
  public static void m365() {}
  public static void m366() {}
  public static void m367() {}
  public static void m368() {}
  public static void m369() {}
  public static void m370() {}
  public static void m371() {}
  public static void m372() {}
  public static void m373() {}
  public static void m374() {}
  public static void m375() {}
  public static void m376() {}
  public static void m377() {}
  public static void m378() {}
  public static void m379() {}
  public static void m380() {}
  public static void m381() {}
  public static void m382() {}
  public static void m383() {}
  public static void m384() {}
  public static void m385() {}
  public static void m386() {}
  public static void m387() {}
  public static void m388() {}
  public static void m389() {}
  public static void m390() {}
  public static void m391() {}
  public static void m392() {}
  public static void m393() {}
  public static void m394() {}
  public static void m395() {}
  public static void m396() {}
  public static void m397() {}
  public static void m398() {}
  public static void m399() {}
  public static void m400() {}
  public static void m401() {}
  public static void m402() {}
  public static void m403() {}
  public static void m404() {}
  public static void m405() {}
  public static void m406() {}
  public static void m407() {}
  public static void m408() {}
  public static void m409() {}
  public static void m410() {}
  public static void m411() {}
  public static void m412() {}
  public static void m413() {}
  public static void m414() {}
  public static void m415() {}
  public static void m416() {}
  public static void m417() {}
  public static void m418() {}
  public static void m419() {}
  public static void m420() {}
  public static void m421() {}
  public static void m422() {}
  public static void m423() {}
  public static void m424() {}
  public static void m425() {}
  public static void m426() {}
  public static void m427() {}
  public static void m428() {}
  public static void m429() {}
  public static void m430() {}
  public static void m431() {}
  public static void m432() {}
  public static void m433() {}
  public static void m434() {}
  public static void m435() {}
  public static void m436() {}
  public static void m437() {}
  public static void m438() {}
  public static void m439() {}
  public static void m440() {}
  public static void m441() {}
  public static void m442() {}
  public static void m443() {}
  public static void m444() {}
  public static void m445() {}
  public static void m446() {}
  public static void m447() {}
  public static void m448() {}
  public static void m449() {}
  public static void m450() {}
  public static void m451() {}
  public static void m452() {}
  public static void m453() {}
  public static void m454() {}
  public static void m455() {}
  public static void m456() {}
  public static void m457() {}
  public static void m458() {}
  public static void m459() {}
  public static void m460() {}
  public static void m461() {}
  public static void m462() {}
  public static void m463() {}
  public static void m464() {}
  public static void m465() {}
  public static void m466() {}
  public static void m467() {}
  public static void m468() {}
  public static void m469() {}
  public static void m470() {}
  public static void m471() {}
  public static void m472() {}
  public static void m473() {}
  public static void m474() {}
  public static void m475() {}
  public static void m476() {}
  public static void m477() {}
  public static void m478() {}
  public static void m479() {}
  public static void m480() {}
  public static void m481() {}
  public static void m482() {}
  public static void m483() {}
  public static void m484() {}
  public static void m485() {}
  public static void m486() {}
  public static void m487() {}
  public static void m488() {}
  public static void m489() {}
  public static void m490() {}
  public static void m491() {}
  public static void m492() {}
  public static void m493() {}
  public static void m494() {}
  public static void m495() {}
  public static void m496() {}
  public static void m497() {}
  public static void m498() {}
  public static void m499() {}
  public static void m500() {}
  public static void m501() {}
  public static void m502() {}
  public static void m503() {}
  public static void m504() {}
  public static void m505() {}
  public static void m506() {}
  public static void m507() {}
  public static void m508() {}
  public static void m509() {}
  public static void m510() {}
  public static void m511() {}
  public static void m512() {}
  public static void m513() {}
  public static void m514() {}
  public static void m515() {}
  public static void m516() {}
  public static void m517() {}
  public static void m518() {}
  public static void m519() {}
  public static void m520() {}
  public static void m521() {}
  public static void m522() {}
  public static void m523() {}
  public static void m524() {}
  public static void m525() {}
  public static void m526() {}
  public static void m527() {}
  public static void m528() {}
  public static void m529() {}
  public static void m530() {}
  public static void m531() {}
  public static void m532() {}
  public static void m533() {}
  public static void m534() {}
  public static void m535() {}
  public static void m536() {}
  public static void m537() {}
  public static void m538() {}
  public static void m539() {}
  public static void m540() {}
  public static void m541() {}
  public static void m542() {}
  public static void m543() {}
  public static void m544() {}
  public static void m545() {}
  public static void m546() {}
  public static void m547() {}
  public static void m548() {}
  public static void m549() {}
  public static void m550() {}
  public static void m551() {}
  public static void m552() {}
  public static void m553() {}
  public static void m554() {}
  public static void m555() {}
  public static void m556() {}
  public static void m557() {}
  public static void m558() {}
  public static void m559() {}
  public static void m560() {}
  public static void m561() {}
  public static void m562() {}
  public static void m563() {}
  public static void m564() {}
  public static void m565() {}
  public static void m566() {}
  public static void m567() {}
  public static void m568() {}
  public static void m569() {}
  public static void m570() {}
  public static void m571() {}
  public static void m572() {}
  public static void m573() {}
  public static void m574() {}
  public static void m575() {}
  public static void m576() {}
  public static void m577() {}
  public static void m578() {}
  public static void m579() {}
  public static void m580() {}
  public static void m581() {}
  public static void m582() {}
  public static void m583() {}
  public static void m584() {}
  public static void m585() {}
  public static void m586() {}
  public static void m587() {}
  public static void m588() {}
  public static void m589() {}
  public static void m590() {}
  public static void m591() {}
  public static void m592() {}
  public static void m593() {}
  public static void m594() {}
  public static void m595() {}
  public static void m596() {}
  public static void m597() {}
  public static void m598() {}
  public static void m599() {}
  public static void m600() {}
  public static void m601() {}
  public static void m602() {}
  public static void m603() {}
  public static void m604() {}
  public static void m605() {}
  public static void m606() {}
  public static void m607() {}
  public static void m608() {}
  public static void m609() {}
  public static void m610() {}
  public static void m611() {}
  public static void m612() {}
  public static void m613() {}
  public static void m614() {}
  public static void m615() {}
  public static void m616() {}
  public static void m617() {}
  public static void m618() {}
  public static void m619() {}
  public static void m620() {}
  public static void m621() {}
  public static void m622() {}
  public static void m623() {}
  public static void m624() {}
  public static void m625() {}
  public static void m626() {}
  public static void m627() {}
  public static void m628() {}
  public static void m629() {}
  public static void m630() {}
  public static void m631() {}
  public static void m632() {}
  public static void m633() {}
  public static void m634() {}
  public static void m635() {}
  public static void m636() {}
  public static void m637() {}
  public static void m638() {}
  public static void m639() {}
  public static void m640() {}
  public static void m641() {}
  public static void m642() {}
  public static void m643() {}
  public static void m644() {}
  public static void m645() {}
  public static void m646() {}
  public static void m647() {}
  public static void m648() {}
  public static void m649() {}
  public static void m650() {}
  public static void m651() {}
  public static void m652() {}
  public static void m653() {}
  public static void m654() {}
  public static void m655() {}
  public static void m656() {}
  public static void m657() {}
  public static void m658() {}
  public static void m659() {}
  public static void m660() {}
  public static void m661() {}
  public static void m662() {}
  public static void m663() {}
  public static void m664() {}
  public static void m665() {}
  public static void m666() {}
  public static void m667() {}
  public static void m668() {}
  public static void m669() {}
  public static void m670() {}
  public static void m671() {}
  public static void m672() {}
  public static void m673() {}
  public static void m674() {}
  public static void m675() {}
  public static void m676() {}
  public static void m677() {}
  public static void m678() {}
  public static void m679() {}
  public static void m680() {}
  public static void m681() {}
  public static void m682() {}
  public static void m683() {}
  public static void m684() {}
  public static void m685() {}
  public static void m686() {}
  public static void m687() {}
  public static void m688() {}
  public static void m689() {}
  public static void m690() {}
  public static void m691() {}
  public static void m692() {}
  public static void m693() {}
  public static void m694() {}
  public static void m695() {}
  public static void m696() {}
  public static void m697() {}
  public static void m698() {}
  public static void m699() {}
  public static void m700() {}
  public static void m701() {}
  public static void m702() {}
  public static void m703() {}
  public static void m704() {}
  public static void m705() {}
  public static void m706() {}
  public static void m707() {}
  public static void m708() {}
  public static void m709() {}
  public static void m710() {}
  public static void m711() {}
  public static void m712() {}
  public static void m713() {}
  public static void m714() {}
  public static void m715() {}
  public static void m716() {}
  public static void m717() {}
  public static void m718() {}
  public static void m719() {}
  public static void m720() {}
  public static void m721() {}
  public static void m722() {}
  public static void m723() {}
  public static void m724() {}
  public static void m725() {}
  public static void m726() {}
  public static void m727() {}
  public static void m728() {}
  public static void m729() {}
  public static void m730() {}
  public static void m731() {}
  public static void m732() {}
  public static void m733() {}
  public static void m734() {}
  public static void m735() {}
  public static void m736() {}
  public static void m737() {}
  public static void m738() {}
  public static void m739() {}
  public static void m740() {}
  public static void m741() {}
  public static void m742() {}
  public static void m743() {}
  public static void m744() {}
  public static void m745() {}
  public static void m746() {}
  public static void m747() {}
  public static void m748() {}
  public static void m749() {}
  public static void m750() {}
  public static void m751() {}
  public static void m752() {}
  public static void m753() {}
  public static void m754() {}
  public static void m755() {}
  public static void m756() {}
  public static void m757() {}
  public static void m758() {}
  public static void m759() {}
  public static void m760() {}
  public static void m761() {}
  public static void m762() {}
  public static void m763() {}
  public static void m764() {}
  public static void m765() {}
  public static void m766() {}
  public static void m767() {}
  public static void m768() {}
  public static void m769() {}
  public static void m770() {}
  public static void m771() {}
  public static void m772() {}
  public static void m773() {}
  public static void m774() {}
  public static void m775() {}
  public static void m776() {}
  public static void m777() {}
  public static void m778() {}
  public static void m779() {}
  public static void m780() {}
  public static void m781() {}
  public static void m782() {}
  public static void m783() {}
  public static void m784() {}
  public static void m785() {}
  public static void m786() {}
  public static void m787() {}
  public static void m788() {}
  public static void m789() {}
  public static void m790() {}
  public static void m791() {}
  public static void m792() {}
  public static void m793() {}
  public static void m794() {}
  public static void m795() {}
  public static void m796() {}
  public static void m797() {}
  public static void m798() {}
  public static void m799() {}
  public static void m800() {}
  public static void m801() {}
  public static void m802() {}
  public static void m803() {}
  public static void m804() {}
  public static void m805() {}
  public static void m806() {}
  public static void m807() {}
  public static void m808() {}
  public static void m809() {}
  public static void m810() {}
  public static void m811() {}
  public static void m812() {}
  public static void m813() {}
  public static void m814() {}
  public static void m815() {}
  public static void m816() {}
  public static void m817() {}
  public static void m818() {}
  public static void m819() {}
  public static void m820() {}
  public static void m821() {}
  public static void m822() {}
  public static void m823() {}
  public static void m824() {}
  public static void m825() {}
  public static void m826() {}
  public static void m827() {}
  public static void m828() {}
  public static void m829() {}
  public static void m830() {}
  public static void m831() {}
  public static void m832() {}
  public static void m833() {}
  public static void m834() {}
  public static void m835() {}
  public static void m836() {}
  public static void m837() {}
  public static void m838() {}
  public static void m839() {}
  public static void m840() {}
  public static void m841() {}
  public static void m842() {}
  public static void m843() {}
  public static void m844() {}
  public static void m845() {}
  public static void m846() {}
  public static void m847() {}
  public static void m848() {}
  public static void m849() {}
  public static void m850() {}
  public static void m851() {}
  public static void m852() {}
  public static void m853() {}
  public static void m854() {}
  public static void m855() {}
  public static void m856() {}
  public static void m857() {}
  public static void m858() {}
  public static void m859() {}
  public static void m860() {}
  public static void m861() {}
  public static void m862() {}
  public static void m863() {}
  public static void m864() {}
  public static void m865() {}
  public static void m866() {}
  public static void m867() {}
  public static void m868() {}
  public static void m869() {}
  public static void m870() {}
  public static void m871() {}
  public static void m872() {}
  public static void m873() {}
  public static void m874() {}
  public static void m875() {}
  public static void m876() {}
  public static void m877() {}
  public static void m878() {}
  public static void m879() {}
  public static void m880() {}
  public static void m881() {}
  public static void m882() {}
  public static void m883() {}
  public static void m884() {}
  public static void m885() {}
  public static void m886() {}
  public static void m887() {}
  public static void m888() {}
  public static void m889() {}
  public static void m890() {}
  public static void m891() {}
  public static void m892() {}
  public static void m893() {}
  public static void m894() {}
  public static void m895() {}
  public static void m896() {}
  public static void m897() {}
  public static void m898() {}
  public static void m899() {}
  public static void m900() {}
  public static void m901() {}
  public static void m902() {}
  public static void m903() {}
  public static void m904() {}
  public static void m905() {}
  public static void m906() {}
  public static void m907() {}
  public static void m908() {}
  public static void m909() {}
  public static void m910() {}
  public static void m911() {}
  public static void m912() {}
  public static void m913() {}
  public static void m914() {}
  public static void m915() {}
  public static void m916() {}
  public static void m917() {}
  public static void m918() {}
  public static void m919() {}
  public static void m920() {}
  public static void m921() {}
  public static void m922() {}
  public static void m923() {}
  public static void m924() {}
  public static void m925() {}
  public static void m926() {}
  public static void m927() {}
  public static void m928() {}
  public static void m929() {}
  public static void m930() {}
  public static void m931() {}
  public static void m932() {}
  public static void m933() {}
  public static void m934() {}
  public static void m935() {}
  public static void m936() {}
  public static void m937() {}
  public static void m938() {}
  public static void m939() {}
  public static void m940() {}
  public static void m941() {}
  public static void m942() {}
  public static void m943() {}
  public static void m944() {}
  public static void m945() {}
  public static void m946() {}
  public static void m947() {}
  public static void m948() {}
  public static void m949() {}
  public static void m950() {}
  public static void m951() {}
  public static void m952() {}
  public static void m953() {}
  public static void m954() {}
  public static void m955() {}
  public static void m956() {}
  public static void m957() {}
  public static void m958() {}
  public static void m959() {}
  public static void m960() {}
  public static void m961() {}
  public static void m962() {}
  public static void m963() {}
  public static void m964() {}
  public static void m965() {}
  public static void m966() {}
  public static void m967() {}
  public static void m968() {}
  public static void m969() {}
  public static void m970() {}
  public static void m971() {}
  public static void m972() {}
  public static void m973() {}
  public static void m974() {}
  public static void m975() {}
  public static void m976() {}
  public static void m977() {}
  public static void m978() {}
  public static void m979() {}
  public static void m980() {}
  public static void m981() {}
  public static void m982() {}
  public static void m983() {}
  public static void m984() {}
  public static void m985() {}
  public static void m986() {}
  public static void m987() {}
  public static void m988() {}
  public static void m989() {}
  public static void m990() {}
  public static void m991() {}
  public static void m992() {}
  public static void m993() {}
  public static void m994() {}
  public static void m995() {}
  public static void m996() {}
  public static void m997() {}
  public static void m998() {}
  public static void m999() {}
}
