/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated by the ProtoZero C compiler plugin.
// Invoked by tools/gen_c_protos
// DO NOT EDIT.
#ifndef INCLUDE_PERFETTO_PUBLIC_PROTOS_CONFIG_PROFILING_JAVA_HPROF_CONFIG_PZC_H_
#define INCLUDE_PERFETTO_PUBLIC_PROTOS_CONFIG_PROFILING_JAVA_HPROF_CONFIG_PZC_H_

#include <stdbool.h>
#include <stdint.h>

#include "perfetto/public/pb_macros.h"

PERFETTO_PB_MSG_DECL(perfetto_protos_JavaHprofConfig_ContinuousDumpConfig);

PERFETTO_PB_MSG(perfetto_protos_JavaHprofConfig);
PERFETTO_PB_FIELD(perfetto_protos_JavaHprofConfig,
                  STRING,
                  const char*,
                  process_cmdline,
                  1);
PERFETTO_PB_FIELD(perfetto_protos_JavaHprofConfig, VARINT, uint64_t, pid, 2);
PERFETTO_PB_FIELD(perfetto_protos_JavaHprofConfig,
                  STRING,
                  const char*,
                  target_installed_by,
                  7);
PERFETTO_PB_FIELD(perfetto_protos_JavaHprofConfig,
                  MSG,
                  perfetto_protos_JavaHprofConfig_ContinuousDumpConfig,
                  continuous_dump_config,
                  3);
PERFETTO_PB_FIELD(perfetto_protos_JavaHprofConfig,
                  VARINT,
                  uint32_t,
                  min_anonymous_memory_kb,
                  4);
PERFETTO_PB_FIELD(perfetto_protos_JavaHprofConfig, VARINT, bool, dump_smaps, 5);
PERFETTO_PB_FIELD(perfetto_protos_JavaHprofConfig,
                  STRING,
                  const char*,
                  ignored_types,
                  6);

PERFETTO_PB_MSG(perfetto_protos_JavaHprofConfig_ContinuousDumpConfig);
PERFETTO_PB_FIELD(perfetto_protos_JavaHprofConfig_ContinuousDumpConfig,
                  VARINT,
                  uint32_t,
                  dump_phase_ms,
                  1);
PERFETTO_PB_FIELD(perfetto_protos_JavaHprofConfig_ContinuousDumpConfig,
                  VARINT,
                  uint32_t,
                  dump_interval_ms,
                  2);
PERFETTO_PB_FIELD(perfetto_protos_JavaHprofConfig_ContinuousDumpConfig,
                  VARINT,
                  bool,
                  scan_pids_only_on_start,
                  3);

#endif  // INCLUDE_PERFETTO_PUBLIC_PROTOS_CONFIG_PROFILING_JAVA_HPROF_CONFIG_PZC_H_
