#!/usr/bin/env python3
#
# Copyright (C) 2021 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

""" This script generates the Android.run-test.bp build file"""

import os, glob, textwrap

def main():
  test_dir = os.path.dirname(__file__)
  with open(os.path.join(test_dir, "Android.run-test.bp"), mode="wt") as f:
    f.write("// This file was generated by {}\n".format(os.path.basename(__file__)))
    tests = glob.glob(os.path.join(test_dir, "[0-9]*"))
    tests = sorted([os.path.basename(t) for t in tests])
    for test in tests:
      f.write(textwrap.dedent("""
        genrule {{
            name: "art-run-test-data-{test}",
            out: ["art-run-test-data-{test}.zip"],
            srcs: ["{test}/**/*"],
            defaults: ["art-run-test-data-defaults"],
            cmd: "$(location run-test-build.py) --out $(out) --test {test} " +
                "--bootclasspath $(location :art-run-test-bootclasspath)",
        }}
        """.format(test=test)))
    tests = ("\n"+" "*8).join(f'":art-run-test-data-{test}",' for test in tests)
    f.write(textwrap.dedent("""
      genrule {{
          name: "art-run-test-data",
          out: ["art-run-test-data.zip"],
          srcs: [
              {tests}
          ],
          tools: ["merge_zips"],
          cmd: "$(location merge_zips) $(out) $(in)",
      }}
      """).format(tests=tests))

if __name__ == "__main__":
  main()
