/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated by the ProtoZero C compiler plugin.
// Invoked by tools/gen_c_protos
// DO NOT EDIT.
#ifndef INCLUDE_PERFETTO_PUBLIC_PROTOS_TRACE_PROFILING_DEOBFUSCATION_PZC_H_
#define INCLUDE_PERFETTO_PUBLIC_PROTOS_TRACE_PROFILING_DEOBFUSCATION_PZC_H_

#include <stdbool.h>
#include <stdint.h>

#include "perfetto/public/pb_macros.h"

PERFETTO_PB_MSG_DECL(perfetto_protos_ObfuscatedClass);
PERFETTO_PB_MSG_DECL(perfetto_protos_ObfuscatedMember);

PERFETTO_PB_MSG(perfetto_protos_DeobfuscationMapping);
PERFETTO_PB_FIELD(perfetto_protos_DeobfuscationMapping,
                  STRING,
                  const char*,
                  package_name,
                  1);
PERFETTO_PB_FIELD(perfetto_protos_DeobfuscationMapping,
                  VARINT,
                  int64_t,
                  version_code,
                  2);
PERFETTO_PB_FIELD(perfetto_protos_DeobfuscationMapping,
                  MSG,
                  perfetto_protos_ObfuscatedClass,
                  obfuscated_classes,
                  3);

PERFETTO_PB_MSG(perfetto_protos_ObfuscatedClass);
PERFETTO_PB_FIELD(perfetto_protos_ObfuscatedClass,
                  STRING,
                  const char*,
                  obfuscated_name,
                  1);
PERFETTO_PB_FIELD(perfetto_protos_ObfuscatedClass,
                  STRING,
                  const char*,
                  deobfuscated_name,
                  2);
PERFETTO_PB_FIELD(perfetto_protos_ObfuscatedClass,
                  MSG,
                  perfetto_protos_ObfuscatedMember,
                  obfuscated_members,
                  3);
PERFETTO_PB_FIELD(perfetto_protos_ObfuscatedClass,
                  MSG,
                  perfetto_protos_ObfuscatedMember,
                  obfuscated_methods,
                  4);

PERFETTO_PB_MSG(perfetto_protos_ObfuscatedMember);
PERFETTO_PB_FIELD(perfetto_protos_ObfuscatedMember,
                  STRING,
                  const char*,
                  obfuscated_name,
                  1);
PERFETTO_PB_FIELD(perfetto_protos_ObfuscatedMember,
                  STRING,
                  const char*,
                  deobfuscated_name,
                  2);

#endif  // INCLUDE_PERFETTO_PUBLIC_PROTOS_TRACE_PROFILING_DEOBFUSCATION_PZC_H_
