/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated by the ProtoZero C compiler plugin.
// Invoked by tools/gen_c_protos
// DO NOT EDIT.
#ifndef INCLUDE_PERFETTO_PUBLIC_PROTOS_TRACE_PROFILING_HEAP_GRAPH_PZC_H_
#define INCLUDE_PERFETTO_PUBLIC_PROTOS_TRACE_PROFILING_HEAP_GRAPH_PZC_H_

#include <stdbool.h>
#include <stdint.h>

#include "perfetto/public/pb_macros.h"
#include "perfetto/public/protos/trace/profiling/deobfuscation.pzc.h"

PERFETTO_PB_MSG_DECL(perfetto_protos_HeapGraphObject);
PERFETTO_PB_MSG_DECL(perfetto_protos_HeapGraphRoot);
PERFETTO_PB_MSG_DECL(perfetto_protos_HeapGraphType);
PERFETTO_PB_MSG_DECL(perfetto_protos_InternedString);

PERFETTO_PB_ENUM_IN_MSG(perfetto_protos_HeapGraphType, Kind){
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphType,
                                  KIND_UNKNOWN) = 0,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphType,
                                  KIND_NORMAL) = 1,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphType,
                                  KIND_NOREFERENCES) = 2,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphType,
                                  KIND_STRING) = 3,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphType,
                                  KIND_ARRAY) = 4,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphType,
                                  KIND_CLASS) = 5,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphType,
                                  KIND_CLASSLOADER) = 6,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphType,
                                  KIND_DEXCACHE) = 7,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphType,
                                  KIND_SOFT_REFERENCE) = 8,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphType,
                                  KIND_WEAK_REFERENCE) = 9,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphType,
                                  KIND_FINALIZER_REFERENCE) = 10,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphType,
                                  KIND_PHANTOM_REFERENCE) = 11,
};

PERFETTO_PB_ENUM_IN_MSG(perfetto_protos_HeapGraphRoot, Type){
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphRoot,
                                  ROOT_UNKNOWN) = 0,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphRoot,
                                  ROOT_JNI_GLOBAL) = 1,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphRoot,
                                  ROOT_JNI_LOCAL) = 2,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphRoot,
                                  ROOT_JAVA_FRAME) = 3,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphRoot,
                                  ROOT_NATIVE_STACK) = 4,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphRoot,
                                  ROOT_STICKY_CLASS) = 5,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphRoot,
                                  ROOT_THREAD_BLOCK) = 6,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphRoot,
                                  ROOT_MONITOR_USED) = 7,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphRoot,
                                  ROOT_THREAD_OBJECT) = 8,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphRoot,
                                  ROOT_INTERNED_STRING) = 9,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphRoot,
                                  ROOT_FINALIZING) = 10,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphRoot,
                                  ROOT_DEBUGGER) = 11,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphRoot,
                                  ROOT_REFERENCE_CLEANUP) = 12,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphRoot,
                                  ROOT_VM_INTERNAL) = 13,
    PERFETTO_PB_ENUM_IN_MSG_ENTRY(perfetto_protos_HeapGraphRoot,
                                  ROOT_JNI_MONITOR) = 14,
};

PERFETTO_PB_MSG(perfetto_protos_HeapGraph);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraph, VARINT, int32_t, pid, 1);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraph,
                  MSG,
                  perfetto_protos_HeapGraphObject,
                  objects,
                  2);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraph,
                  MSG,
                  perfetto_protos_HeapGraphRoot,
                  roots,
                  7);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraph,
                  MSG,
                  perfetto_protos_HeapGraphType,
                  types,
                  9);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraph,
                  MSG,
                  perfetto_protos_InternedString,
                  field_names,
                  4);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraph,
                  MSG,
                  perfetto_protos_InternedString,
                  location_names,
                  8);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraph, VARINT, bool, continued, 5);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraph, VARINT, uint64_t, index, 6);

PERFETTO_PB_MSG(perfetto_protos_HeapGraphObject);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraphObject, VARINT, uint64_t, id, 1);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraphObject,
                  VARINT,
                  uint64_t,
                  id_delta,
                  7);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraphObject,
                  VARINT,
                  uint64_t,
                  type_id,
                  2);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraphObject,
                  VARINT,
                  uint64_t,
                  self_size,
                  3);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraphObject,
                  VARINT,
                  uint64_t,
                  reference_field_id_base,
                  6);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraphObject,
                  PACKED,
                  Uint64,
                  reference_field_id,
                  4);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraphObject,
                  PACKED,
                  Uint64,
                  reference_object_id,
                  5);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraphObject,
                  VARINT,
                  int64_t,
                  native_allocation_registry_size_field,
                  8);

PERFETTO_PB_MSG(perfetto_protos_HeapGraphType);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraphType, VARINT, uint64_t, id, 1);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraphType,
                  VARINT,
                  uint64_t,
                  location_id,
                  2);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraphType,
                  STRING,
                  const char*,
                  class_name,
                  3);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraphType,
                  VARINT,
                  uint64_t,
                  object_size,
                  4);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraphType,
                  VARINT,
                  uint64_t,
                  superclass_id,
                  5);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraphType,
                  PACKED,
                  Uint64,
                  reference_field_id,
                  6);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraphType,
                  VARINT,
                  enum perfetto_protos_HeapGraphType_Kind,
                  kind,
                  7);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraphType,
                  VARINT,
                  uint64_t,
                  classloader_id,
                  8);

PERFETTO_PB_MSG(perfetto_protos_HeapGraphRoot);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraphRoot, PACKED, Uint64, object_ids, 1);
PERFETTO_PB_FIELD(perfetto_protos_HeapGraphRoot,
                  VARINT,
                  enum perfetto_protos_HeapGraphRoot_Type,
                  root_type,
                  2);

#endif  // INCLUDE_PERFETTO_PUBLIC_PROTOS_TRACE_PROFILING_HEAP_GRAPH_PZC_H_
