/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated by the ProtoZero C compiler plugin.
// Invoked by tools/gen_c_protos
// DO NOT EDIT.
#ifndef INCLUDE_PERFETTO_PUBLIC_PROTOS_TRACE_PROFILING_SMAPS_PZC_H_
#define INCLUDE_PERFETTO_PUBLIC_PROTOS_TRACE_PROFILING_SMAPS_PZC_H_

#include <stdbool.h>
#include <stdint.h>

#include "perfetto/public/pb_macros.h"

PERFETTO_PB_MSG_DECL(perfetto_protos_SmapsEntry);

PERFETTO_PB_MSG(perfetto_protos_SmapsPacket);
PERFETTO_PB_FIELD(perfetto_protos_SmapsPacket, VARINT, uint32_t, pid, 1);
PERFETTO_PB_FIELD(perfetto_protos_SmapsPacket,
                  MSG,
                  perfetto_protos_SmapsEntry,
                  entries,
                  2);

PERFETTO_PB_MSG(perfetto_protos_SmapsEntry);
PERFETTO_PB_FIELD(perfetto_protos_SmapsEntry, STRING, const char*, path, 1);
PERFETTO_PB_FIELD(perfetto_protos_SmapsEntry, VARINT, uint64_t, size_kb, 2);
PERFETTO_PB_FIELD(perfetto_protos_SmapsEntry,
                  VARINT,
                  uint64_t,
                  private_dirty_kb,
                  3);
PERFETTO_PB_FIELD(perfetto_protos_SmapsEntry, VARINT, uint64_t, swap_kb, 4);
PERFETTO_PB_FIELD(perfetto_protos_SmapsEntry,
                  STRING,
                  const char*,
                  file_name,
                  5);
PERFETTO_PB_FIELD(perfetto_protos_SmapsEntry,
                  VARINT,
                  uint64_t,
                  start_address,
                  6);
PERFETTO_PB_FIELD(perfetto_protos_SmapsEntry,
                  VARINT,
                  uint64_t,
                  module_timestamp,
                  7);
PERFETTO_PB_FIELD(perfetto_protos_SmapsEntry,
                  STRING,
                  const char*,
                  module_debugid,
                  8);
PERFETTO_PB_FIELD(perfetto_protos_SmapsEntry,
                  STRING,
                  const char*,
                  module_debug_path,
                  9);
PERFETTO_PB_FIELD(perfetto_protos_SmapsEntry,
                  VARINT,
                  uint32_t,
                  protection_flags,
                  10);
PERFETTO_PB_FIELD(perfetto_protos_SmapsEntry,
                  VARINT,
                  uint64_t,
                  private_clean_resident_kb,
                  11);
PERFETTO_PB_FIELD(perfetto_protos_SmapsEntry,
                  VARINT,
                  uint64_t,
                  shared_dirty_resident_kb,
                  12);
PERFETTO_PB_FIELD(perfetto_protos_SmapsEntry,
                  VARINT,
                  uint64_t,
                  shared_clean_resident_kb,
                  13);
PERFETTO_PB_FIELD(perfetto_protos_SmapsEntry, VARINT, uint64_t, locked_kb, 14);
PERFETTO_PB_FIELD(perfetto_protos_SmapsEntry,
                  VARINT,
                  uint64_t,
                  proportional_resident_kb,
                  15);

#endif  // INCLUDE_PERFETTO_PUBLIC_PROTOS_TRACE_PROFILING_SMAPS_PZC_H_
